name: Deploy to Azure
on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: SharpAITest-API
  DOTNET_VERSION: '9.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: List files
      run: |
        echo "Repository structure:"
        ls -lR
        echo "---------------------"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build API
      working-directory: SharpAITest/SharpAITest.API 
      run: dotnet build --configuration Release

    - name: Publish
      working-directory: SharpAITest/SharpAITest.API
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.SHARP_AI_TEST_PUBLISH_PROFILE }}
        package: SharpAITest/SharpAITest.API/publish